### ISSUE TITLE
systemd profiles are not supported

### ISSUE THREAD

**Issue by sjug** [sormy/gentoo-ami-builder#1]
Unable to get past installation of portage repo since amd64-systemd profile does not have `usr/`.

```
 *   Installing portage repo...
 *     Initializing...
 *     Process has failed with error code 1: cp -f /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf                                    
       > cp: cannot stat ‘/mnt/gentoo/usr/share/portage/config/repos.conf’: No such file or directory                                                                                
 *   Phase bootstrap has failed
```

**Comment by sormy** [comment]
This is something that I expected. Need to fix. By the way, why do you need systemd-flavored profile on AWS?

**Comment by sormy** [comment]
For this particular problem this is something wrong with upstream stage3, see <http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-systemd>

Stage3 is just 1.2 KB :-)

By the way, when upstream will fix the issue I expect that this builder won't work well on phases where rc-update is used because this is specific to OpenRC.

**Comment by sjug** [comment]
Ah yes, you're right sorry for the issue spam the latest stage3 is quality.

I would never run a desktop or server without systemd. I see so we need to replace those with something like `systemctl enable`?

**Comment by sormy** [comment]
- modify rc-update with systemctl enable
- wrap ec2 init script into systemd unit, ec2 init script should initialize hostname slightly differently (thru systemd)
- genkernel won't build bootable kernel with systemd, need to use genkernel-next

there could be probably something else, need to test

**Comment by sormy** [comment]
Here is an upstream bug: https://bugs.gentoo.org/664398

**Comment by sjug** [comment]
Thanks @sormy, we can close this issue as it was specifically due to the bad stage3.

**Comment by sormy** [comment]
I renamed the issue because systemd support still should be fixed

**Comment by sormy** [comment]
Alright, I added support for systemd in gentoo-vbox-builder. Need to port code to gentoo-ami-builder.

**Comment by sormy** [comment]
v1.0.2 can produce systemd AMI images

**Comment by sjug** [comment]
Great thanks @sormy, I'll give it a try

**Comment by sjug** [comment]
@sormy, what is the syntax for `${GENTOO_PROFILE}` as usually you `eselect profile set <number>`?

**Comment by sormy** [comment]
It should be enough to use `./gentoo-ami-builder.sh --key-pair "Your Key Name" --gentoo-stage3 amd64-systemd`. 

I renamed gentoo-profile to gentoo-stage3 and introduced new key gentoo-profile that could be used to switch profile on the fly.

`./gentoo-ami-builder.sh --help` will show available profiles if you would like to switch profile on the fly.

**Comment by sormy** [comment]
Let me know if it works for you and if we could close the issue.

**Comment by sjug** [comment]
@sormy working as expected, thanks for the support
