### ISSUE TITLE
`sfdisk` broken on create partition (invalid option --label)

### ISSUE THREAD

**Issue by k2t0f12d** [sormy/gentoo-ami-builder#11]
ap-southeast-2
ami-09cc0712275eacf93

`sfdisk` choked on create partition.
Manually edited this change using `parted` (possibly also not the best fix as we care about source and target sizes)
`phase2-prepare-root.sh`
```
# create partition with the same size on first disk to use `dd` later
#sfdisk --dump "$PRI_DISK_DEV" | grep "$PRI_ROOT_DEV\b" | grep -o 'size=[^,]*' | \
#    eexec sfdisk --label gpt "$AUX_DISK_DEV"
PRI_DISK_SIZE=$(parted -a optimal $PRI_ROOT_DEV unit B -- print | grep "^Disk /" | awk -F' ' '{print $3}')
einfo "Original partition size: $PRI_DISK_SIZE..."
einfo "Creating disk label..."
eqexec parted -a optimal $AUX_DISK_DEV unit B -- mklabel gpt
einfo "Creating target partition..."
parted -a optimal $AUX_DISK_DEV unit B -- mkpart pri 0% $PRI_DISK_SIZE
```

**Comment by sormy** [comment]
I have just executed image builder for amd64 on us-east-1 and did not get any errors. Could you please confirm the command line you used to build the image. Also `chocked` output will be extremely useful to understand the root cause.

**Comment by sormy** [comment]
Unfortunately, I was not able to reproduce the issue. Latest version of builder was able to get amd64 image without sfdisk issues. I have fixed a few other minor fixes as well, so rerun the builder.

**Comment by sormy** [comment]
No response, resolving
