### ISSUE TITLE
Systemd networking broken on user phase

### ISSUE THREAD

**Issue by AZMCode** [sormy/gentoo-ami-builder#15]
I've temporarily fixed the issue by removing [this line](https://github.com/sormy/gentoo-ami-builder/blob/690c33fddc74854e284029cb06f738682a6a433f/lib/phase3-build-root.sh#L305) from the phase 3 script, but I assume it has a purpose after all.

**Comment by sormy** [comment]
Could you please provide error log

**Comment by AZMCode** [comment]
That's weird. I literally have no logs to share in this respect, as everything worked out fine up until the user phase. I understand if you have to close the issue due to lack of repro.

**Comment by AZMCode** [comment]
As of now I'm busy getting my current user phase script to work using the fix described, but I might come back to this and provide the log and further experimentation to see what causes the bug.

**Comment by frostynova** [comment]
Met this problem too

CLI: ./gentoo-ami-builder.sh --region ap-southeast-1 --key-pair gentoo --spot-instance false --gentoo-stage3 amd64-systemd  --gentoo-profile default/linux/amd64/17.1/systemd

No error output during script execution. But using this ami to boot a new instance, "/run/systemd/resolve/resolv.conf" is missing.

After "systemctl restart systemd-resolved", everything is ok.

**Comment by sormy** [comment]
might be related to ap-southeast-1, reopening, but will test after holidays

**Comment by sormy** [comment]
Seems like it is working now, feel free to reopen with more details
