### ISSUE TITLE
Digest filenames updated .DIGESTS.asc no longer exists

### ISSUE THREAD

**Issue by MrKnarfy** [sormy/gentoo-ami-builder#17]
And it should be replaced by .DIGESTS

I am trying to create a pull request.

**Comment by MrKnarfy** [comment]
I have no idea how to add the pull request here...

**Comment by sormy** [comment]
Thanks for reporting, I will take a look on

**Comment by sormy** [comment]
seems like it works based on latest PR, resolving, feel free to reopen with more details
