### ISSUE TITLE
grub-install failed due to error embedding is not possible

### ISSUE THREAD

**Issue by zypeh** [sormy/gentoo-ami-builder#24]
```
 *   Mounting primary disk...
 *     Mounting root...
 *     Mounting proc/sys/dev...
 *   Cleaning primary disk...
 *   Fixing boot on primary disk...
 *     Installing bootloader into MBR...
 *     Process has failed with error code 1: chroot /mnt/gentoo grub-install /dev/nvme0n1
       > Installing for i386-pc platform.
       > grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
       > grub-install: error: embedding is not possible, but this is required for cross-disk install.
 *   Phase bootstrap has failed
 * Terminating instance...
 ```
 
 I got the issue when building on `C6in.2xlarge` instance. Is there any solution / pointer for me to solve this issue?

**Comment by sormy** [comment]
is this specific to c6in (nitro)? have you tried c6i.2xlarge?

**Comment by zypeh** [comment]
C6i also has nitro system. But I am trying C6i.2xlarge now.

**Comment by zypeh** [comment]
It seems to me that it that for the same instance (C6in) I was able to run chroot /mnt/gentoo grub-install /dev/nvme0n1 without error. I manually check the 5th phrase via entering the command line by line.

At the same time my C6i.2xlarge build is successfully. I will run another test with C6in again to see this is consistent, then this issue is safe to close.

**Comment by zypeh** [comment]
I have tested with the `C6in.2xlarge` again, same params and got no error. It is good to close this issue.
