### ISSUE TITLE
Phase bootstrap has failed

### ISSUE THREAD

**Issue by cagkanm** [sormy/gentoo-ami-builder#9]
First of all, I had to change the AWS AMI id as it couldn't find a matching one so I looked that the available AMI and used that instead. I mentioned this as I am not sure if this could be the cause of the problem below;

`* PHASE 2: Prepare Root
 *   Synchronizing time...
 *   Process has failed with error code 1: yum -y -q install ntp
     > Existing lock /var/run/yum.pid: another copy is running as pid 2990.
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:10 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:12 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:14 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:16 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:18 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:20 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:22 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:24 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:26 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:28 ago
     >     State  : Sleeping, pid: 2990
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  31 M RSS (323 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:30 ago
     >     State  : Sleeping, pid: 2990
     > Existing lock /var/run/yum.pid: another copy is running as pid 2994.
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:32 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:34 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:36 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:38 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:40 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:42 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:44 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:46 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:48 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:50 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:52 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:54 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:56 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 00:58 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 01:00 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 01:02 ago
     >     State  : Sleeping, pid: 2994
     > Another app is currently holding the yum lock; waiting for it to exit...
     >   The other application is: yum
     >     Memory :  35 M RSS (328 MB VSZ)
     >     Started: Fri Dec  4 12:53:48 2020 - 01:04 ago
     >     State  : Sleeping, pid: 2994
     > 
     > 
     >  One of the configured repositories failed (Unknown),
     >  and yum doesn't have enough cached data to continue. At this point the only
     >  safe thing yum can do is fail. There are a few ways to work "fix" this:
     > 
     >      1. Contact the upstream for the repository and get them to fix the problem.
     > 
     >      2. Reconfigure the baseurl/etc. for the repository, to point to a working
     >         upstream. This is most often useful if you are using a newer
     >         distribution release than is supported by the repository (and the
     >         packages for the previous distribution release still work).
     > 
     >      3. Run the command with the repository temporarily disabled
     >             yum --disablerepo=<repoid> ...
     > 
     >      4. Disable the repository permanently, so yum won't use it by default. Yum
     >         will then just ignore the repository until you permanently enable it
     >         again or use --enablerepo for temporary usage:
     > 
     >             yum-config-manager --disable <repoid>
     >         or
     >             subscription-manager repos --disable=<repoid>
     > 
     >      5. Configure the failing repository to be skipped, if it is unavailable.
     >         Note that yum will try to contact the repo. when it runs most commands,
     >         so will have to try and fail each time (and thus. yum will be be much
     >         slower). If it is a very temporary problem though, this is often a nice
     >         compromise:
     > 
     >             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
     > 
     > Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
     > Could not retrieve mirrorlist http://amazonlinux.eu-west-2.amazonaws.com/2/core/latest/x86_64/mirror.list error was
     > 12: Timeout on http://amazonlinux.eu-west-2.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Connection timed out after 5000 milliseconds')
 *   Phase bootstrap has failed
 * Terminating instance...
`

**Comment by sormy** [comment]
What region are your trying to build image? eu-west-2? AMI images are different per region. This is definitely a gap in builder. I will take a look.

**Comment by sormy** [comment]
Please try with these images (pick your region and platform):

us-east-1 x86_64 ami-04bf6dcdc9ab498ca
us-east-1 arm64 ami-09e7aedfda734b173
us-east-2 x86_64 ami-0b0f4c27376f8aa79
us-east-2 arm64 ami-07bc0b7b8fe124499
us-west-1 x86_64 ami-000279759c4819ddf
us-west-1 arm64 ami-05c5afbe9410a4cde
us-west-2 x86_64 ami-07a0da1997b55b23e
us-west-2 arm64 ami-0787fda5708b00aa3
af-south-1 x86_64 None
af-south-1 arm64 None
ap-east-1 x86_64 None
ap-east-1 arm64 None
ap-south-1 x86_64 ami-026669ec456129a70
ap-south-1 arm64 ami-06a2b4acacc88730a
ap-northeast-2 x86_64 ami-06f3207f56dc1ca18
ap-northeast-2 arm64 ami-0ac13ed6ae1ad748c
ap-southeast-1 x86_64 ami-03faaf9cde2b38e9f
ap-southeast-1 arm64 ami-0d8566954ee6c6bb1
ap-southeast-2 x86_64 ami-076e39b6b14e3bb20
ap-southeast-2 arm64 ami-09d24eea676a7e71a
ap-northeast-1 x86_64 ami-034968955444c1fd9
ap-northeast-1 arm64 ami-0ede32f8db20757b3
ca-central-1 x86_64 ami-0c9bfc21ac5bf10eb
ca-central-1 arm64 ami-04bc32a3660b07a1d
eu-central-1 x86_64 ami-0649a2ac1437cf3b7
eu-central-1 arm64 ami-07fa567d4d357ca5f
eu-west-1 x86_64 ami-014ce76919b528bff
eu-west-1 arm64 ami-0f706da0eaaffbaaf
eu-west-2 x86_64 ami-0271d331ac7dab654
eu-west-2 arm64 ami-046b480143dbc626a
eu-south-1 x86_64 None
eu-south-1 arm64 None
eu-west-3 x86_64 ami-0c3d23d707737957d
eu-west-3 arm64 ami-01e06f7d74ba1664f
eu-north-1 x86_64 ami-0b26bf4b43c8d995d
eu-north-1 arm64 ami-01847a84a2fc5fd37
me-south-1 x86_64 None
me-south-1 arm64 None
sa-east-1 x86_64 ami-08f7f9fcedda2e070
sa-east-1 arm64 ami-08f725fac57cfbcc8

**Comment by sormy** [comment]
For `eu-west-2` your command line should look like: `AWS_DEFAULT_REGION="eu-west-2" ./gentoo-ami-builder.sh --amazon-image-id ami-0271d331ac7dab654 --key-pair "Your Key Pair Name"`.

Let me know if it works.

I'm going to update the build with multi region support based on your feedback.

**Comment by sormy** [comment]
I have updated builder to version 1.1.2. Not it accept region from command line and can automatically detect Amazon Linux 2 AMI in target region for target architecture.

Please try: `./gentoo-ami-builder.sh --region eu-west-2 --key-pair "Your Key Pair Name"`

**Comment by sormy** [comment]
The real issue why your provisioning has failed I think is because security group attached to EC2 instance doesn't allow to communicate with public internet.

**Comment by cagkanm** [comment]
I had already edited the .sh file with the correct AMI from eu-west-2. The region flag and auto-detection is a good idea..

The problem was, in fact, the default VPC I was using. It didn't allow any traffic out.

Thanks for your help.
